### ISSUE TITLE
Code availability

### ISSUE THREAD

**Issue by agitter** [TencentAI4S/CD-GPT#1]
I found your bioRxiv [preprint](https://doi.org/10.1101/2024.06.24.600337), and the model looks interesting. I saw in the code availbility statement
> The codebase and model checkpoint for CD-GPT is publicly available at https://github.com/TencentAI4S/CD-GPT.

Could you please elaborate on what you plan to release here?

**Comment by HexagonStar** [comment]
Hi Gitter, sorry for the delayed response! We have released the code and checkpoints of CD-GPT recently and will refine the README to include more **demos** and **illustrations** of our model. 
Thanks for your interest in our work and look forward to your feedback!

**Comment by agitter** [comment]
Excellent, thanks for the explanation
