### ISSUE TITLE
generate CDS

### ISSUE THREAD

**Issue by terry-r123** [TencentAI4S/CD-GPT#3]
Thanks for your awesome work.

I'd like to know how to use CD-GPT to generate the codon sequence from protein.

Thanks so much.

**Comment by HexagonStar** [comment]
Hi Terry, thanks for your interest in our work! We have released the necessary weight files and a tutorial. You can refer to `generate_example.ipynb` for more guidance. Feel free to raise issues if you encounter any problems while using CD-GPT.

**Comment by terry-r123** [comment]
Thanks for your reply and guidance! It looks very great.
